steps:
- name: gcr.io/cloud-builders/docker
  args:
    ["build", "-t", "asia-south1-docker.pkg.dev/$PROJECT_ID/docker-repo/llm-app", "."]

- name: gcr.io/cloud-builders/docker
  args:
    ["push", "asia-south1-docker.pkg.dev/$PROJECT_ID/docker-repo/llm-app"]

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "run",
      "deploy",
      "llm-app",
      "--image",
      "asia-south1-docker.pkg.dev/$PROJECT_ID/docker-repo/llm-app",
      "--region",
      "asia-south1",
      "--platform",
      "managed",
      "--allow-unauthenticated"
    ]

options:
  logging: CLOUD_LOGGING_ONLY
